trigger: 
- master
pool:
 name: 'local'
stages:
  - stage: Build
    jobs:
    - job:
      displayName: 'Maven Build'
      steps:
      - task: Maven@4
        inputs:
          mavenPomFile: 'pom.xml'
          goals: 'clean package -Dmaven.test.skip=true'
          publishJUnitResults: false
          javaHomeOption: 'JDKVersion'
          mavenVersionOption: 'Default'
          mavenAuthenticateFeed: false
          effectivePomSkip: false
          sonarQubeRunAnalysis: false
  - stage: PublishArtifact
    jobs:
    - job:
      steps:
      - task: PublishPipelineArtifact@1
        inputs:
          targetPath: '/home/ec2-user/myagent/_work/2/s/target/'
          artifact: 'app.jar'
          publishLocation: 'pipeline'